### ISSUE TITLE
problems of "pip install textflint''

### ISSUE THREAD

**Issue by zhangxiao002266** [textflint/textflint#22]
I have successfully install textflint. But when I import textflint, it have the error ：ModuleNotFoundError: No module named 'textflint.lib'. Could you help me solve this problem? Thank you.

**Comment by BeyonderXX** [comment]
It looks like an environmental problem or incorrect usage.

To reproduce the error, please provide your system and environment information, better with code.

**Comment by zhangxiao002266** [comment]
Here is the error when I import textflint. My environment is linux and python 3.7.0 

Python 3.7.0 (default, Oct  9 2018, 10:31:47) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import textflint
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anaconda3/envs/textflint/lib/python3.7/site-packages/textflint/__init__.py", line 16, in <module>
    from .input_layer import *
  File "/home/anaconda3/envs/textflint/lib/python3.7/site-packages/textflint/input_layer/__init__.py", line 3, in <module>
    from .dataset import Dataset
  File "/home/anaconda3/envs/textflint/lib/python3.7/site-packages/textflint/input_layer/dataset/__init__.py", line 1, in <module>
    from .dataset import Dataset, sample_map
  File "/home/anaconda3/envs/textflint/lib/python3.7/site-packages/textflint/input_layer/dataset/dataset.py", line 23, in <module>
    sample_map = get_sample_map()
  File "/home/anaconda3/envs/textflint/lib/python3.7/site-packages/textflint/input_layer/dataset/dataset.py", line 20, in get_sample_map
    filter_str='_sample')
  File "/home/anaconda3/envs/textflint/lib/python3.7/site-packages/textflint/common/utils/load.py", line 34, in task_class_load
    for module in modules:
  File "/home/anaconda3/envs/textflint/lib/python3.7/site-packages/textflint/common/utils/load.py", line 27, in module_loader
    yield importlib.import_module(module_name)
  File "/home/anaconda3/envs/textflint/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'textflint.lib'

**Comment by BeyonderXX** [comment]
This is an error caused by the _importlib_ of the python built-in package. 
It is recommended that the python version is greater than 3.7.10, or directly install the latest anaconda.

Please refer to: https://github.com/textflint/textflint/issues/8
