### ISSUE TITLE
Run Quick start Error

### ISSUE THREAD

**Issue by ValarMorghulis2018** [textflint/textflint#6]
`Traceback (most recent call last):
  File "d:/pyscript/test_text.py", line 1, in <module>
    from TextFlint import Engine
  File "D:\pyscript\work\lib\site-packages\textflint-0.0.1-py3.6.egg\TextFlint\__init__.py", line 7, in <module>
    from .generation_layer.generator import Generator
  File "D:\pyscript\work\lib\site-packages\textflint-0.0.1-py3.6.egg\TextFlint\generation_layer\generator\__init__.py", line 1, in <module>
    from .generator import Generator
  File "D:\pyscript\work\lib\site-packages\textflint-0.0.1-py3.6.egg\TextFlint\generation_layer\generator\generator.py", line 12, in <module>
    from ...input_layer.dataset import Dataset
  File "D:\pyscript\work\lib\site-packages\textflint-0.0.1-py3.6.egg\TextFlint\input_layer\dataset\__init__.py", line 1, in <module>
    from .dataset import Dataset, sample_map
  File "D:\pyscript\work\lib\site-packages\textflint-0.0.1-py3.6.egg\TextFlint\input_layer\dataset\dataset.py", line 23, in <module>
    sample_map = get_sample_map()
  File "D:\pyscript\work\lib\site-packages\textflint-0.0.1-py3.6.egg\TextFlint\input_layer\dataset\dataset.py", line 20, in get_sample_map
    filter_str='_sample')
  File "D:\pyscript\work\lib\site-packages\textflint-0.0.1-py3.6.egg\TextFlint\common\utils\load.py", line 34, in task_class_load
    for module in modules:
  File "D:\pyscript\work\lib\site-packages\textflint-0.0.1-py3.6.egg\TextFlint\common\utils\load.py", line 27, in module_loader
    yield importlib.import_module(module_name)
  File "c:\users\huisuan016\appdata\local\programs\python\python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'TextFlint-0'`

**Comment by BeyonderXX** [comment]
Hi,

Recommed install with `pip` command

**Comment by anaivebird** [comment]
TextFlint has not be tested for Windows 10 + Python 3.6 Environment. (Especially considering the dependencies of Textflint may not support it.)
Currently, TextFlint  works well for Linux(and it is recommended). You could test it with `!pip install textflint` on [Google Colab](https://colab.research.google.com/)

**Comment by BeyonderXX** [comment]
Thank you for your feedback!

TextFlint have not support python 3.6, recommend install with python version >= 3.7

**Comment by ValarMorghulis2018** [comment]
Thank you for your reply!
